typography_spectrum: 0.7721994612365961
content_rating:
  adult: false
color:
  brandStrength: 0.6711927659343928
  lightness: 0.7384724607691169
  saturation: 0.696986204944551
  rhythmicContrast: 0.6751752013806254
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
opengraph:
  type: ''
layout_spectrum: 0.554613383486867
author:
  email: dvanzant@investorideas.com
  name: 'Investor Ideas  Newswire '
  url: ' http://investorideasnewswire.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e447317c-4988-4b1a-a6e2-f6c410fa13ca.png
name: 'Investor Ideas Newswire  '
navigation:
  - name: About newswire
    url: 'http://www.investorideas.com/News-Upload/'
    type: external
  - name: Disclaimer
    url: 'http://www.investorideas.com/About/Disclaimer.asp'
    type: external
  - name: YouTube Investorideas
    url: 'https://www.youtube.com/c/Investorideas'
    type: external
  - name: 'Investorideas Twitter '
    url: 'https://twitter.com/Investorideas'
    type: external
title: news that inspires big ideas
description: 'Today''s Investor Ideas '
